# Generated by Django 3.2.16 on 2023-02-27 05:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено ли?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('created_by_id', models.UUIDField(null=True, verbose_name='Создатель')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('updated_by_id', models.UUIDField(null=True, verbose_name='Кто изменил')),
                ('name', models.CharField(max_length=250, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория сферы деятельности',
                'verbose_name_plural': 'категории сферы деятельности',
                'db_table': 'directory_activity_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено ли?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('created_by_id', models.UUIDField(null=True, verbose_name='Создатель')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('updated_by_id', models.UUIDField(null=True, verbose_name='Кто изменил')),
                ('name', models.CharField(max_length=250, verbose_name='название')),
            ],
            options={
                'verbose_name': 'система автоматизации',
                'verbose_name_plural': 'системы автоматизации',
                'db_table': 'directory_automation_system',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено ли?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('created_by_id', models.UUIDField(null=True, verbose_name='Создатель')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('updated_by_id', models.UUIDField(null=True, verbose_name='Кто изменил')),
                ('name', models.CharField(max_length=300, verbose_name='название')),
            ],
            options={
                'verbose_name': 'цель участия',
                'verbose_name_plural': 'цели участия',
                'db_table': 'directory_participation_purpose',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProblemOrTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено ли?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('created_by_id', models.UUIDField(null=True, verbose_name='Создатель')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('updated_by_id', models.UUIDField(null=True, verbose_name='Кто изменил')),
                ('name', models.CharField(max_length=300, verbose_name='название')),
            ],
            options={
                'verbose_name': 'проблема или задача',
                'verbose_name_plural': 'проблемы или задачи',
                'db_table': 'directory_problem_or_task',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено ли?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('created_by_id', models.UUIDField(null=True, verbose_name='Создатель')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('updated_by_id', models.UUIDField(null=True, verbose_name='Кто изменил')),
                ('name', models.CharField(max_length=250, verbose_name='название')),
                ('activity_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', related_query_name='activity', to='directory.activitycategory', verbose_name='категория сферы деятельности')),
            ],
            options={
                'verbose_name': 'сфера деятельности',
                'verbose_name_plural': 'сферы деятельности',
                'db_table': 'directory_activity',
                'ordering': ['name'],
            },
        ),
    ]
