# Generated by Django 3.2.16 on 2023-03-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationsystem',
            name='is_other',
            field=models.BooleanField(default=False, verbose_name='другое'),
        ),
    ]
