# Generated by Django 3.2.16 on 2023-02-27 05:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено ли?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('created_by_id', models.UUIDField(null=True, verbose_name='Создатель')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('updated_by_id', models.UUIDField(null=True, verbose_name='Кто изменил')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='название курса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание курса')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='дата завершения')),
                ('course_assessment_link', models.URLField(blank=True, null=True, verbose_name='ссылка на оценку курса')),
                ('knowledge_assessment_link', models.URLField(blank=True, null=True, verbose_name='ссылка на оценку знаний')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'courses_course',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено ли?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('created_by_id', models.UUIDField(null=True, verbose_name='Создатель')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('updated_by_id', models.UUIDField(null=True, verbose_name='Кто изменил')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='дата завершения')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='время завершения')),
                ('is_complete', models.BooleanField(default=False, verbose_name='курс завершен')),
            ],
            options={
                'verbose_name': 'расписание курса',
                'verbose_name_plural': 'расписания курсов',
                'db_table': 'courses_course_schedule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено ли?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('created_by_id', models.UUIDField(null=True, verbose_name='Создатель')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('updated_by_id', models.UUIDField(null=True, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Группа абитуриентов',
                'verbose_name_plural': 'Группы абитуриентов',
                'db_table': 'courses_course_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено ли?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('created_by_id', models.UUIDField(null=True, verbose_name='Создатель')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('updated_by_id', models.UUIDField(null=True, verbose_name='Кто изменил')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'спецификация курса',
                'verbose_name_plural': 'спецификация курса',
                'db_table': 'courses_course_specification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSessionListener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено ли?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('created_by_id', models.UUIDField(null=True, verbose_name='Создатель')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('updated_by_id', models.UUIDField(null=True, verbose_name='Кто изменил')),
                ('course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursesession')),
            ],
            options={
                'verbose_name': 'абитуриент группы',
                'verbose_name_plural': 'абитуриенты группы',
                'db_table': 'courses_course_session_listener',
                'ordering': ['created_at'],
            },
        ),
    ]
