# Generated by Django 3.2.16 on 2023-02-27 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesessionlistener',
            name='listener',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollees.tempenrollee'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='course_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sessions', related_query_name='course_session', to='courses.courseschedule', verbose_name='расписание курса'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='temp_enrollee',
            field=models.ManyToManyField(related_name='course_sessions', related_query_name='course_session', through='courses.CourseSessionListener', to='enrollees.TempEnrollee', verbose_name='абитуриенты'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='курс'),
        ),
    ]
