# Generated by Django 3.2.16 on 2023-02-27 11:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20230227_1701'),
        ('courses', '0004_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено ли?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('created_by_id', models.UUIDField(null=True, verbose_name='Создатель')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('updated_by_id', models.UUIDField(null=True, verbose_name='Кто изменил')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория видео курса',
                'verbose_name_plural': 'категории видео курсов',
                'db_table': 'courses_video_course_category',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='courseschedule',
            options={'ordering': ['created_at'], 'verbose_name': 'расписание курса', 'verbose_name_plural': 'расписания курсов'},
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_schedules', related_query_name='course_schedule', to='courses.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedules', related_query_name='course_schedule', to='teachers.teacher', verbose_name='тренер'),
        ),
        migrations.CreateModel(
            name='VideoCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено ли?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('created_by_id', models.UUIDField(null=True, verbose_name='Создатель')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('updated_by_id', models.UUIDField(null=True, verbose_name='Кто изменил')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('video_course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_courses', related_query_name='video_course', to='courses.videocoursecategory', verbose_name='категория видео курса')),
            ],
            options={
                'verbose_name': 'видео курс',
                'verbose_name_plural': 'видео курсы',
                'db_table': 'courses_video_course',
                'ordering': ['created_at'],
            },
        ),
    ]
