# Generated by Django 3.2.16 on 2023-02-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20230227_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocourse',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на видео'),
        ),
    ]
