# Generated by Django 3.2.16 on 2023-03-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_videocourse_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursespecification',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/course_photo'),
        ),
    ]
