# Generated by Django 3.2.16 on 2023-10-06 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_coursespecification_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesession',
            name='temp_enrollee',
        ),
        migrations.RemoveField(
            model_name='coursesessionlistener',
            name='listener',
        ),
    ]
