# Generated by Django 3.2.16 on 2023-10-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20231006_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursespecification',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/media/course_photo', verbose_name='фото'),
        ),
    ]
