exclude: '.git|migrations'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      -   id: pyupgrade
          args: [--py38-plus]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.12.0
    hooks:
      - id: django-upgrade
        args: [--target-version, '3.2']

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
