# Generated by Django 3.2.16 on 2023-02-27 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollees', '0001_initial'),
        ('listener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollee',
            name='listener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollees', related_query_name='enrollee', to='listener.listener', verbose_name='слушатель'),
        ),
    ]
