# Generated by Django 3.2.16 on 2023-03-31 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollees', '0003_auto_20230302_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempenrollee',
            name='identification_number',
            field=models.CharField(default='', help_text='Юридического лица', max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Неправильный идентификационный номер.', 'invalid')], verbose_name='ИИН/БИН'),
        ),
        migrations.AlterField(
            model_name='tempenrollee',
            name='phone_number',
            field=models.CharField(help_text='без +7, например: 7071231212.', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Неправильный номер телефона.', 'invalid')], verbose_name='Контактный телефон'),
        ),
    ]
