# Generated by Django 3.2.16 on 2023-04-05 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollees', '0004_auto_20230331_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempenrollee',
            name='identification_number',
            field=models.CharField(default='', help_text='Предприятие', max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Неправильный идентификационный номер.', 'invalid')], verbose_name='ИИН/БИН'),
        ),
    ]
