# Generated by Django 3.2.16 on 2023-09-25 05:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20230302_1315'),
        ('enrollees', '0006_alter_tempenrollee_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempenrollee',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_enrollees', related_query_name='temp_enrollee', to='directory.activity', verbose_name='смотреть стр. СФЕРА_ДЕЯТЕЛЬНОСТИ'),
        ),
        migrations.AlterField(
            model_name='tempenrollee',
            name='another_automation_system',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Какие системы автоматизации Вы используете в компании'),
        ),
        migrations.AlterField(
            model_name='tempenrollee',
            name='another_participation_purpose',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ожидаемые результаты от участия в Программе «Almaty Business 2023»'),
        ),
        migrations.AlterField(
            model_name='tempenrollee',
            name='automation_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_enrollees', related_query_name='temp_enrollee', to='directory.automationsystem', verbose_name='Используете ли Вы системы автоматизации в своем бизнесе?'),
        ),
        migrations.AlterField(
            model_name='tempenrollee',
            name='email',
            field=models.CharField(max_length=250, verbose_name='Электронный адрес Участника'),
        ),
        migrations.AlterField(
            model_name='tempenrollee',
            name='full_name',
            field=models.CharField(max_length=500, verbose_name='ФИО Участника (полностью)'),
        ),
        migrations.AlterField(
            model_name='tempenrollee',
            name='identification_number',
            field=models.CharField(default='', help_text='Организации', max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Неправильный идентификационный номер.', 'invalid')], verbose_name='ИИН/БИН компании'),
        ),
        migrations.AlterField(
            model_name='tempenrollee',
            name='is_recording_average_check',
            field=models.BooleanField(default=False, verbose_name='Укажите сумму среднемесячного чека в вашей компании'),
        ),
        migrations.AlterField(
            model_name='tempenrollee',
            name='is_recording_customers',
            field=models.BooleanField(default=False, verbose_name='Укажите среднемесячное количество клиентов Вашей компании'),
        ),
        migrations.AlterField(
            model_name='tempenrollee',
            name='is_used_automation',
            field=models.BooleanField(default=False, verbose_name='Применяете ли Вы автоматизацию в своей деятельности'),
        ),
        migrations.AlterField(
            model_name='tempenrollee',
            name='lang',
            field=models.CharField(choices=[('KK', 'Қазақ тілі'), ('RU', 'Русский язык')], default='RU', max_length=50, verbose_name='Язык обучения'),
        ),
        migrations.AlterField(
            model_name='tempenrollee',
            name='number_of_completed_years',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='целые числа без 1,999 и минуса'),
        ),
        migrations.AlterField(
            model_name='tempenrollee',
            name='participation_purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_enrollees', related_query_name='temp_enrollee', to='directory.participationpurpose', verbose_name='Ожидаемые результаты от участия в Программе «Almaty Business 2023»'),
        ),
        migrations.AlterField(
            model_name='tempenrollee',
            name='phone_number',
            field=models.CharField(help_text='без +7, например: 7071231212.', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Неправильный номер телефона.', 'invalid')], verbose_name='Номер телефона с WatsApp'),
        ),
    ]
