# Generated by Django 3.2.16 on 2023-09-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollees', '0007_auto_20230925_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempenrollee',
            name='is_recording_average_check',
            field=models.CharField(default=False, max_length=500, verbose_name='Укажите сумму среднемесячного чека в вашей компании'),
        ),
        migrations.AlterField(
            model_name='tempenrollee',
            name='is_recording_customers',
            field=models.CharField(default=False, max_length=500, verbose_name='Укажите среднемесячное количество клиентов Вашей компании'),
        ),
    ]
