# Generated by Django 3.2.16 on 2023-09-28 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollees', '0008_auto_20230925_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempenrollee',
            name='course_schedule',
        ),
    ]
