# Generated by Django 3.2.16 on 2023-10-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollees', '0009_remove_tempenrollee_course_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollee',
            name='course_schedule',
        ),
        migrations.AddField(
            model_name='tempenrollee',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает рассмотрения'), ('ACCEPTED', 'Одобрено'), ('REJECTED', 'Недействительная анкета')], default='PENDING', max_length=50, verbose_name='Статус'),
        ),
    ]
