# Generated by Django 3.2.16 on 2023-10-04 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollees', '0010_auto_20231002_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempenrollee',
            name='another_automation_system',
        ),
        migrations.RemoveField(
            model_name='tempenrollee',
            name='another_participation_purpose',
        ),
        migrations.RemoveField(
            model_name='tempenrollee',
            name='another_problem_or_task',
        ),
    ]
