# Generated by Django 3.2.16 on 2023-10-04 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollees', '0011_auto_20231004_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempenrollee',
            name='is_used_automation',
        ),
    ]
