# Generated by Django 3.2.16 on 2023-10-06 06:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20231006_1223'),
        ('enrollees', '0012_remove_tempenrollee_is_used_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempenrollee',
            name='course_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_enrollees', related_query_name='temp_enrollee', to='courses.course', verbose_name='Какие курсы Вы выбираете для обучения?'),
        ),
        migrations.AlterField(
            model_name='tempenrollee',
            name='number_of_completed_years',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Количество полных лет работы бизнеса'),
        ),
        migrations.AlterField(
            model_name='tempenrollee',
            name='phone_number',
            field=models.CharField(help_text='без +7, например: 7071231212.', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Неправильный номер телефона.', 'invalid')], verbose_name='Номер телефона с WhatsApp'),
        ),
    ]
