# Generated by Django 3.2.16 on 2023-10-10 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollees', '0013_auto_20231006_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempenrollee',
            name='identification_number',
            field=models.CharField(default='', max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Неправильный идентификационный номер.', 'invalid')], verbose_name='ИИН/БИН компании'),
        ),
    ]
