# Generated by Django 3.2.16 on 2023-10-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollees', '0014_alter_tempenrollee_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempenrollee',
            name='number_of_completed_years',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Количество полных лет работы компания'),
        ),
    ]
