# Generated by Django 3.2.16 on 2023-02-27 05:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено ли?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('created_by_id', models.UUIDField(null=True, verbose_name='Создатель')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('updated_by_id', models.UUIDField(null=True, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Слушатель',
                'verbose_name_plural': 'Слушатели',
                'db_table': 'listeners_listener',
                'ordering': ['-created_at'],
            },
        ),
    ]
