# Generated by Django 3.2.16 on 2023-02-27 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listener',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listener', to=settings.AUTH_USER_MODEL),
        ),
    ]
