# Generated by Django 3.2.16 on 2023-10-09 03:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Биография'),
        ),
    ]
